[package]
name = "sfutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "sfu"
path = "src/main.rs"

[dependencies]
console = "0.15.7"

